### ISSUE TITLE
Since the recent update, my charts on other tabs don't display.

### ISSUE THREAD

**Issue by adavie1** [ankane/vue-chartkick#57] opened 2018-06-27 13:42 UTC
I'm using elements-ui to create a series of tabs, using a prior release- charts on non-visible tabs, showed up fine when the tab was selected. Did an upgrade a few days back.

I'm using **Charts.js**.

The recent update broke something. The first tab shows the charts fine. Selecting other tabs, the charts don't show.
**First tab:**
![image](https://user-images.githubusercontent.com/3030402/41977656-7325dada-7a52-11e8-8edd-f60d3aa8b1d7.png)

**Second tab (no hot deploy changes yet):**
![image](https://user-images.githubusercontent.com/3030402/41977710-9610cb90-7a52-11e8-9e41-e7f6193c28e1.png)

**After hot deploy changes (just changed something trivial like the thousands separator):**
![image](https://user-images.githubusercontent.com/3030402/41977753-bda2a0a2-7a52-11e8-8772-341f5cfb8610.png)

Using `yarn run dev` if I change something like `:donut="false"` to `:donut="true"` in the code, then the chart shows. Some kind of refresh issue perhaps?

**Comment by ankane** [comment] 2018-06-27 20:39
Hey @adavie1, what version were you on before and what version did you upgrade to?

**Comment by adavie1** [comment] 2018-07-09 02:35
Hi @ankane apologies for the late reply. Version 0.3.1. I've since downgraded back to that so that charts show for the client.

**Comment by ankane** [comment] 2018-07-09 02:47
No worries. The issue is fixed in the latest version. Try upgrading to 0.4.0.

**Closed by ankane** 2018-07-09 02:47 UTC
